language: python
python:
 # - "2.6"
 - "2.7"
 # - "3.3"
 # - "3.4"
install:
    - pip install -e .
    - pip install coverage coveralls
    - start_cms_project.py testing testing/ --with-people --with-faqs --with-jobs --skip-frontend
script: coverage run --source=cms testing/manage.py test
notifications:
  slack: onespacemedia:NufeDxb1m4D0UkuQh1O0m9qt
  email: false
after_success:
  - coveralls
