language: python
python:
 # - "2.6"
 - "2.7"
 # - "3.3"
 # - "3.4"
install:
    - pip install -e .
    - start_cms_project.py testing .
script: python manage.py test
notifications:
  slack: onespacemedia:NufeDxb1m4D0UkuQh1O0m9qt
  email: false
