version: 2
jobs:
  test_python_3.6:
    working_directory: ~/cms
    docker:
      - image: circleci/python:3.6.2
        environment:
          - DB_USER=root
          - DB_NAME=cms
      - image: circleci/postgres:9.5.10
        environment:
          - POSTGRES_USER=root
          - POSTGRES_DB=cms
    steps:
      - checkout
      - run:
          name: install python dependencies
          command: |
            sudo apt-get install libgeoip-dev -y
            pip install -e .[testing]
      - run:
          name: pytest
          command: |
            pytest --cov=cms -n auto --create-db --nomigrations

workflows:
  version: 2
  test:
    jobs:
      - test_python_3.6
